name: Generate Snake Animation

# Jalankan setiap hari atau secara manual
on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Ambil repository kamu
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate file SVG animasi snake
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ouchycode   # GANTI dengan username GitHub kamu
          outputs: dist/github-contribution-grid-snake.svg

      # Deploy SVG hasilnya ke branch "output"
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
